theme: jekyll-theme-minimal

title: [archzero | ArchLinuxArm]
description: [Basic NAS built on Raspberry Pi Zero W]
logo: [https://github.com/alexandrebobkov/archzero/blob/master/img/logo.png]
show_downloads: [false]
